/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import java.sql.*;
import br.com.genius.dal.ModuloConexao;
import javax.swing.JTextField;

/**
 *
 * @author Dino
 */

public class Tela_Login extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    PreparedStatement pst2 = null;
    ResultSet rs = null;
    ResultSet rs2 = null;

    /**
     * Creates new form Tela_Login
     */
    public Tela_Login() {
        initComponents();
        conexao = ModuloConexao.conector(); // "conexao" é a variavel que vai receber o banco de dados
        // a condição abaixo informa se o servidor está off e bloqueia o botão se estiver
        if (conexao == null){
            JOptionPane.showMessageDialog(null, "Erro ao tentar se comunicar com o servidor");
            btnLogin.setEnabled(false);
            txtStatus.setText("Servidor: Offline");
            //System.exit(0); (descontinuado)
        } else {
            txtStatus.setText("Servidor: Online");
        }
        getRootPane().setDefaultButton(btnLogin); // define o botão "btnLogin" como botão principal da tela, quando apertar enter faz entrar no programa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jLabel1.setText("Login");

        jLabel2.setText("Senha");

        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtStatus.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(txtStatus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtStatus)
                        .addContainerGap())))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Dino-orange-icon.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Magneto", 0, 24)); // NOI18N
        jLabel4.setText("Dino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(466, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // modelo 2 de validação de login abaixo
    public void logar() {        // tirar do objeto "btnLoginActionPerformed" se não funcionar
        String sqlFuncionarios = "SELECT * FROM genius.funcionarios WHERE Login_fun= ? AND Senha_fun= ?";
        
        try {
            // as linhas abaixo preparam para a consulta ao banco em função do que foi
            // digitado nas caixas de texto. O "?" é substituido pelo conteúdo das variáveis
            pst = conexao.prepareStatement(sqlFuncionarios);
            pst.setString(1, txtLogin.getText());
            pst.setString(2, txtSenha.getText());
            // a linha abaixo executa a query (consulta ao banco de dados)
            rs = pst.executeQuery();
            // se existir o usuário e senha
            if (rs.next()) {
                String IdFuncao = rs.getString(29); // cria a variavel função que vai armazenar o dado da coluna 29 da linha correspondente ao usuário informado (função do funcionário)
                            
                                // vai tentar usar o Id da função para buscar o nome da função
                try {
                    String sqlFuncao = "SELECT * FROM genius.funcoes WHERE Id= ?"; // define o lugar de onde buscar a informação no MySQL
                    pst2 = conexao.prepareStatement(sqlFuncao);
                    pst2.setInt(1, Integer.parseInt(IdFuncao));
                    // a linha abaixo executa a query (consulta ao banco de dados)
                    rs2 = pst2.executeQuery();
                    // se encontrar o Id da função
                    if (rs2.next()) {
                    
                
                        String funcao = rs2.getString(2);
                        System.out.println(funcao);
                        
                        // Vai bloquear a entrada de funcionários sem permissão e voltar para a tela de login
                        if (funcao.equals("ADMINISTRADOR")) {
                            
                        Tela_Principal tela = new Tela_Principal(); // cria o novo objeto tela da classe Tela_Principal
                        dispose(); // fecha a tela de login
                        tela.setExtendedState(Tela_Principal.MAXIMIZED_BOTH); // faz o JFrame tela iniciar maximizado
                        tela.setVisible(true); // mostra o objeto "tela"
                        
                        // a cessão abaixo libera o uso de diferentes recursos para diferentes funcoes 
                        //Ainda não escrito
                        
                        JOptionPane.showMessageDialog(null, "Bem vindo(a) " + txtLogin.getText());
                        } else {
                            dispose();
                            JOptionPane.showMessageDialog(null, "Usuário sem permissão para ecessar o sistema");
                            new Tela_Login().setVisible(true);
                        }
                    }
                } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Usuario com problemas no cadastro, o sistema será fechado");
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
            System.exit(0);
            
                }
                
            
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Login ou Senha incorretos");

            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
    
}
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
// modelo 1 de validação de login:
      //  String login = "dino";
        
      //  if (txtLogin.getText().equals(login) && txtSenha.getText().equals("2308")) {
            
      //      Tela_Principal tela = new Tela_Principal();
      //      dispose();
      //      tela.setVisible(true);
      //     JOptionPane.showMessageDialog(null, "Bem vindo dino");
            
      //  } else {
                
      //      JOptionPane.showMessageDialog(null, "Login ou Senha incorretos");
      //  }
        
// modelo 2 de validação de login:
        logar(); // inicia o método "logar"

        

    }//GEN-LAST:event_btnLoginActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    protected static javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
